[explorer] fix: Expired mosaic namespace.
symbol/explorer pull request #1193
Opened 2024-07-25 08:57 UTC by AnthonyLaw

## What was the issue?
- Mosaic alias expired, transaction page can not load the page.

## What's the fix?
- Added transactionLocation params in `resolveMosaicId` method.
- Implement mosaic resolution statement query in the `resolveMosaicId` method.
- Refactor `getTransactionMosaicInfoAndNamespace` method to process the transaction.
- Refactor `getMosaicInfoAndNamespace` method to accept mosaicID and transactionLocation params.
- Refactor affected transaction methods in CreateTransaction object such as `mosaicDefinition`, `mosaicSupplyChange`, `mosaicAddressRestriction`, and `mosaicMetadata`

2024-08-07 03:36 UTC, Wayonb requested changes

2024-08-07 03:36 UTC, Wayonb commented on src/helper.js
> +			if (!transactionInfo?.height)
When will the transactionInfo not have a height? 🤔

2025-01-16 16:15 UTC, AnthonyLaw commented on src/helper.js
> +			if (!transactionInfo?.height)
You are right, even for the unconfirmed transactions, the height is `0`.
I will remove it

2025-01-16 18:14 UTC, AnthonyLaw commented on src/helper.js
> +		}
I will add the throw error here.

2025-01-18 14:54 UTC, Wayonb submitted a review, later dismissed
👍🏾

2025-01-22 14:19 UTC, Wayonb reviewed
👍🏾

2025-01-22 17:02 UTC, Wayonb approved these changes
👍🏾

2025-01-22 17:05 UTC, merged